Repository knowsys/nemo, pull requests merged in 2023-09, with the labels that each got.

#350 Fix typo in README.md
  README.md
Labels: bug, documentation

#351 ensure filename is shown in the error message
  nemo-cli/src/main.rs
  nemo-physical/src/error.rs
  nemo/src/api.rs
  nemo/src/io/resource_providers/file.rs
  nemo/src/io/resource_providers/http.rs
Labels: enhancement, io

#356 Avoid building wasm-bindgen-cli
  flake.lock
  flake.nix
Labels: enhancement, infrastructure

#362 Validate predicate usage against declared arity
  nemo/src/program_analysis/analysis.rs
Labels: bug, program analysis

#363 Implement Tracing
  nemo-cli/src/cli.rs
  nemo-cli/src/main.rs
  nemo-physical/src/datatypes/storage_value.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/management/execution_plan.rs
  nemo-physical/src/tabular/operations/materialize.rs
  nemo-physical/src/tabular/table_types/trie.rs
  nemo-physical/src/tabular/traits/table.rs
  nemo/src/error.rs
  nemo/src/execution.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/execution/tracing.rs
  nemo/src/execution/tracing/trace.rs
  nemo/src/io/parser.rs
  nemo/src/model.rs
  nemo/src/model/chase_model/atom.rs
  nemo/src/model/rule_model/atom.rs
  nemo/src/model/rule_model/filter.rs
  nemo/src/model/rule_model/literal.rs
  nemo/src/model/rule_model/program.rs
  nemo/src/model/rule_model/rule.rs
  nemo/src/model/rule_model/term.rs
  nemo/src/model/rule_model/term_operation.rs
  nemo/src/model/types/primitive_logical_value.rs
  nemo/src/model/types/primitive_types.rs
  nemo/src/table_manager.rs
Labels: enhancement
