Repository knowsys/nemo, pull requests merged in 2023-05, with the labels that each got.

#221 Fix bug 214
  src/physical/dictionary/prefixed_string_dictionary.rs
Labels: bug

#231 Fix triescanprune advance return value
  src/physical/columnar/operations/columnscan_prune.rs
  src/physical/columnar/traits/columnscan.rs
  src/physical/tabular/operations/triescan_prune.rs
Labels: bug, physical

#232 Doc/io
  resources/doc/examples/city_population.csv
  src/io.rs
  src/io/dsv.rs
  src/io/output_file_manager.rs
  src/logical/builder_proxy.rs
  src/logical/model.rs
  src/logical/permutator.rs
  src/physical/builder_proxy.rs
  src/physical/columnar.rs
  src/physical/columnar/column_types.rs
  src/physical/columnar/column_types/interval.rs
  src/physical/columnar/operations/columnscan_cast.rs
  src/physical/columnar/operations/columnscan_minus.rs
  src/physical/columnar/traits.rs
  src/physical/columnar/traits/column.rs
  src/physical/columnar/traits/columnscan.rs
  src/physical/datatypes/storage_value.rs
  src/physical/management/execution_plan.rs
  src/physical/tabular/operations.rs
  src/physical/tabular/operations/materialize.rs
  src/physical/tabular/operations/triescan_join.rs
  src/physical/tabular/table_types.rs
  src/physical/tabular/traits.rs
  src/physical/util.rs
  src/physical/util/mapping/ordered_choice.rs
Labels: documentation

#237 API with opaque types
  src/api.rs
  src/lib.rs
Labels: enhancement, api

#240 Decentralized api
  flake.nix
  src/api.rs
  src/app.rs
  src/cli.rs
  src/error.rs
  src/io.rs
  src/io/output_file_manager.rs
  src/io/parser.rs
  src/logical/execution.rs
  src/logical/execution/execution_engine.rs
  src/logical/model.rs
  src/main.rs
  tests/blackbox_integration.rs
Labels: enhancement, api

#233 Refactor (split) rule model
  .github/workflows/pr.yml
  src/logical/model.rs
  src/logical/model/chase_model.rs
  src/logical/model/rule_model.rs
  src/physical/tabular/operations/triescan_prune.rs
Labels: enhancement

#249 create rust-toolchain.toml
  rust-toolchain.toml
Labels: enhancement

#252 Add `nemo-python` bindings crate
  Cargo.lock
  Cargo.toml
  nemo-python/.gitignore
  nemo-python/Cargo.toml
  nemo-python/README.md
  nemo-python/pyproject.toml
  nemo-python/src/lib.rs
  nemo/src/lib.rs
Labels: enhancement, api
