Repository knowsys/nemo, pull requests merged in 2023-06, with the labels that each got.

#256 bump pyo3 version to 0.19
  Cargo.lock
  nemo-python/Cargo.toml
Labels: dependency

#262 Update flake.nix
  flake.nix
Labels: infrastructure

#274 Unpin nightly toolchain
  rust-toolchain.toml
Labels: infrastructure

#276 Feature/272 variable comparisons
  nemo-physical/src/columnar/operations.rs
  nemo-physical/src/columnar/operations/columnscan_equal_value.rs
  nemo-physical/src/columnar/operations/columnscan_restrict_values.rs
  nemo-physical/src/columnar/traits/columnscan.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/management/execution_plan.rs
  nemo-physical/src/tabular/operations.rs
  nemo-physical/src/tabular/operations/triescan_prune.rs
  nemo-physical/src/tabular/operations/triescan_select.rs
  nemo-physical/src/tabular/traits/partial_trie_scan.rs
  nemo-physical/src/util.rs
  nemo-physical/src/util/interval.rs
  nemo/src/execution/planning/plan_util.rs
  nemo/src/program_analysis/analysis.rs
  resources/testcases/variable_comparisons/run.rls
  resources/testcases/variable_comparisons/run/combine.csv
  resources/testcases/variable_comparisons/run/contra.csv
  resources/testcases/variable_comparisons/run/equal.csv
  resources/testcases/variable_comparisons/run/g_eq.csv
  resources/testcases/variable_comparisons/run/g_un.csv
  resources/testcases/variable_comparisons/run/l_eq.csv
  resources/testcases/variable_comparisons/run/l_un.csv
  resources/testcases/variable_comparisons/run/multi.csv
  resources/testcases/variable_comparisons/run/r_xy.csv
  resources/testcases/variable_comparisons/run/r_yx.csv
Labels: enhancement

#279 Cache the nix builds
  .github/workflows/nix.yml
Labels: infrastructure

#243 Add logical string type
  nemo-cli/src/main.rs
  nemo-python/src/lib.rs
  nemo-python/tests/test_example.py
  nemo/src/api.rs
  nemo/src/builder_proxy.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/io/dsv.rs
  nemo/src/io/parser.rs
  nemo/src/model/chase_model.rs
  nemo/src/model/rule_model.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/variable_order.rs
  nemo/src/types.rs
  resources/testcases/datalog_constants/run.rls
  resources/testcases/datalog_constants/sources/dataA.csv
  resources/testcases/datalog_constants/sources/dataB.csv
  resources/testcases/datatype_normalization/run.rls
  resources/testcases/datatype_normalization/run/c.csv
  resources/testcases/datatype_normalization/sources/b.csv
  resources/testcases/lcs-diff-computation/lcs10-doca.csv
  resources/testcases/lcs-diff-computation/lcs10-docb.csv
  resources/testcases/lcs-diff-computation/lcs10-letters.csv
  resources/testcases/lcs-diff-computation/lcs10-succ.csv
  resources/testcases/lcs-diff-computation/run-lcs-10.rls
  resources/testcases/load_multiple/run.rls
  resources/testcases/load_multiple/sources/dataA.csv
  resources/testcases/load_multiple/sources/dataB.csv
  resources/testcases/load_multiple/sources/dataC.csv
  resources/testcases/ntriples/example2.rls
  resources/testcases/restricted_block/run.rls
  resources/testcases/restricted_datalog_head/run.rls
  resources/testcases/restricted_head_constant/run.rls
  resources/testcases/restricted_multihead/run.rls
  resources/testcases/restricted_multinulls/run.rls
  resources/testcases/restricted_multipieces/run.rls
  resources/testcases/restricted_recursive/run.rls
  resources/testcases/restricted_simple/run.rls
  resources/testcases/restricted_simple/sources/data.csv
  resources/testcases/stratified_negation/run.rls
Labels: enhancement, logical, type system

#281 allow converting decimal and integer ground terms to float64
  nemo/src/types.rs
Labels: enhancement, type system
