Repository knowsys/nemo, pull requests merged in 2023-07, with the labels that each got.

#289 fix CI errors
  nemo-cli/src/main.rs
  nemo-physical/src/columnar/adaptive_column_builder.rs
  nemo-physical/src/columnar/operations/columnscan_reorder.rs
  nemo-physical/src/dictionary/value_serializer.rs
  nemo-physical/src/management/execution_plan.rs
  nemo-physical/src/permutator.rs
  nemo-physical/src/tabular/operations/materialize.rs
  nemo-physical/src/tabular/operations/triescan_append.rs
  nemo/src/api.rs
  nemo/src/builder_proxy.rs
  nemo/src/io/dsv.rs
  nemo/src/io/parser.rs
  nemo/src/io/parser/sparql.rs
  nemo/src/io/parser/turtle.rs
  nemo/src/program_analysis/variable_order.rs
  nemo/src/table_manager.rs
Labels: infrastructure

#295 Allow column-wise iteration of full tables
  nemo-physical/src/datatypes/data_value.rs
  nemo-physical/src/datatypes/storage_value.rs
  nemo-physical/src/dictionary/value_serializer.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/tabular/table_types/trie.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/table_manager.rs
Labels: enhancement, physical

#299 Report progress while loading DSV and RDF files
  nemo/src/io/formats.rs
  nemo/src/io/formats/dsv.rs
  nemo/src/io/formats/rdf_triples.rs
Labels: enhancement, io

#301 refactor rule model, add nested types
  nemo-wasm/src/lib.rs
  nemo/benches/operations.rs
  nemo/src/builder_proxy.rs
  nemo/src/error.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/execution/planning/arithmetic.rs
  nemo/src/execution/planning/negation.rs
  nemo/src/execution/planning/plan_util.rs
  nemo/src/execution/planning/seminaive_join.rs
  nemo/src/io/formats/dsv.rs
  nemo/src/io/formats/rdf_triples.rs
  nemo/src/io/input_manager.rs
  nemo/src/io/parser.rs
  nemo/src/io/parser/types.rs
  nemo/src/lib.rs
  nemo/src/model.rs
  nemo/src/model/chase_model.rs
  nemo/src/model/chase_model/atom.rs
  nemo/src/model/chase_model/program.rs
  nemo/src/model/chase_model/rule.rs
  nemo/src/model/rule_model.rs
  nemo/src/model/rule_model/atom.rs
  nemo/src/model/rule_model/datasource.rs
  nemo/src/model/rule_model/filter.rs
  nemo/src/model/rule_model/literal.rs
  nemo/src/model/rule_model/program.rs
  nemo/src/model/rule_model/rule.rs
  nemo/src/model/rule_model/term.rs
  nemo/src/model/rule_model/term_operation.rs
  nemo/src/model/types.rs
  nemo/src/model/types/complex_types.rs
  nemo/src/model/types/primitive_types.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/variable_order.rs
  nemo/src/table_manager.rs
Labels: enhancement, type system

#302 Split benches into distinct crate
  .gitignore
  Cargo.lock
  Cargo.toml
  nemo-benches/Cargo.toml
  nemo-benches/README.md
  nemo-benches/benches/operations.rs
  nemo-benches/benches/seek.rs
  nemo-benches/benches/seek_iai.rs
  nemo/Cargo.toml
Labels: enhancement, crate

#306 Speed up loading of `any` Columns
  nemo/src/builder_proxy.rs
  nemo/src/io/formats/rdf_triples.rs
  nemo/src/io/parser.rs
  nemo/src/io/parser/types.rs
  nemo/src/model/rule_model/term.rs
Labels: CSV, io, rdf, regression

#307 use flate2::read::MultiGzDecoder instead of flate2::read::GzDecoder
  nemo/src/io/resource_providers.rs
Labels: enhancement, io

#297 Implement abstraction for mapping from logical to physical layer and vice-versa
  Cargo.lock
  nemo-benches/benches/operations.rs
  nemo-physical/src/builder_proxy.rs
  nemo-physical/src/datatypes/data_value.rs
  nemo-physical/src/dictionary/value_serializer.rs
  nemo-physical/src/error.rs
  nemo-physical/src/tabular/operations/triescan_append.rs
  nemo-python/src/lib.rs
  nemo-python/tests/test_blackbox.py
  nemo-python/tests/test_example.py
  nemo-wasm/src/lib.rs
  nemo/Cargo.toml
  nemo/src/builder_proxy.rs
  nemo/src/error.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/io/formats/dsv.rs
  nemo/src/io/formats/rdf_triples.rs
  nemo/src/io/input_manager.rs
  nemo/src/io/parser.rs
  nemo/src/model/rule_model/datasource.rs
  nemo/src/model/rule_model/term.rs
  nemo/src/model/types.rs
  nemo/src/model/types/error.rs
  nemo/src/model/types/primitive_logical_value.rs
  nemo/src/model/types/primitive_types.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/variable_order.rs
Labels: technical-debt, logical, type system

#315 Shrink columns on construction
  nemo-physical/src/columnar/column_types/rle.rs
  nemo-physical/src/columnar/column_types/vector.rs
Labels: enhancement, physical

#319 Add simple benchmarks for in-/output handling
  nemo-benches/Cargo.toml
  nemo-benches/benches/input.rs
  nemo-benches/benches/output.rs
  nemo/src/builder_proxy.rs
  nemo/src/lib.rs
Labels: enhancement, logical, tests

#320 Dynamic source loading
  nemo-benches/benches/operations.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/table_reader.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/io/formats/dsv.rs
  nemo/src/io/formats/rdf_triples.rs
  nemo/src/io/input_manager.rs
  nemo/src/io/parser.rs
  nemo/src/model/rule_model/datasource.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/variable_order.rs
Labels: io

#331 Add fallback for conversion of large numeric datavalue literals
  flake.lock
  nemo-physical/src/error.rs
  nemo/src/builder_proxy.rs
  nemo/src/io/formats/rdf_triples.rs
  nemo/src/io/parser.rs
  nemo/src/model/rule_model/term.rs
  nemo/src/model/types/error.rs
  nemo/src/model/types/primitive_logical_value.rs
Labels: bug, io, rdf

#333 Unsafe negation
  nemo-physical/src/management/execution_plan.rs
  nemo-physical/src/tabular/operations/triescan_append.rs
  nemo-physical/src/tabular/operations/triescan_join.rs
  nemo-physical/src/tabular/operations/triescan_minus.rs
  nemo-physical/src/tabular/operations/triescan_nulls.rs
  nemo-physical/src/tabular/operations/triescan_project.rs
  nemo-physical/src/tabular/operations/triescan_prune.rs
  nemo-physical/src/tabular/operations/triescan_select.rs
  nemo-physical/src/tabular/operations/triescan_union.rs
  nemo-physical/src/tabular/table_types/trie.rs
  nemo-physical/src/tabular/traits/partial_trie_scan.rs
  nemo/src/io/parser/types.rs
  nemo/src/model/rule_model/rule.rs
  resources/testcases/basic_negation/run.rls
  resources/testcases/basic_negation/run/projectedX.csv
  resources/testcases/basic_negation/run/projectedXY.csv
  resources/testcases/basic_negation/run/projectedXZ.csv
  resources/testcases/basic_negation/run/projectedY.csv
  resources/testcases/basic_negation/run/projectedYZ.csv
  resources/testcases/basic_negation/run/projectedZ.csv
Labels: enhancement, logical, planning engine
