Repository knowsys/nemo, pull requests merged in 2023-10, with the labels that each got.

#369 Fix trie scan prune up
  nemo-physical/src/columnar/operations/columnscan_prune.rs
  nemo-physical/src/tabular/operations/triescan_prune.rs
Labels: bug, physical

#375 remove obsolete tagged_tree module
  nemo-physical/src/util.rs
  nemo-physical/src/util/tagged_tree.rs
Labels: technical-debt

#380 fix skipping over values in constraint implementation
  nemo-physical/src/columnar/operations/columnscan_restrict_values.rs
  resources/testcases/arithmetic/constraint.rls
  resources/testcases/arithmetic/constraint/r0.csv
  resources/testcases/arithmetic/constraint/r1.csv
  resources/testcases/arithmetic/constraint/r2.csv
  resources/testcases/arithmetic/head.rls
  resources/testcases/arithmetic/head/r0.csv
  resources/testcases/arithmetic/head/r1.csv
  resources/testcases/arithmetic/head/r2.csv
  resources/testcases/arithmetic/head/r3.csv
Labels: bug, physical

#383 Fix: sync pycodestyle settings in nix flake check
  flake.nix
Labels: bug, tests

#384 update pyO3 to 0.20
  Cargo.lock
  nemo-python/Cargo.toml
Labels: dependency, python

#385 Configure pycodestyle to avoid mismatching line lengths
  flake.nix
  nemo-python/pyproject.toml
  nemo-python/setup.cfg
Labels: bug, infrastructure

#386 Bump dependencies
  Cargo.lock
  nemo-benches/Cargo.toml
  nemo-benches/benches/operations.rs
Labels: dependency

#389 Don't run miri on slow unit tests
  nemo/src/io/parser.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/variable_order.rs
Labels: enhancement, tests, infrastructure

#372 Respect literals (and facts) when inferring types
  nemo/src/model/chase_model/atom.rs
  nemo/src/model/chase_model/program.rs
  nemo/src/model/rule_model/aggregate.rs
  nemo/src/model/rule_model/numeric_literal.rs
  nemo/src/model/rule_model/term.rs
  nemo/src/model/types/primitive_types.rs
  nemo/src/program_analysis.rs
  nemo/src/program_analysis/analysis.rs
  nemo/src/program_analysis/type_inference.rs
  nemo/src/program_analysis/type_inference/position_graph.rs
  nemo/src/program_analysis/type_inference/type_requirement.rs
  resources/testcases/datatype_inference_consistency/no-source.rls
  resources/testcases/datatype_inference_consistency/no-source/p.csv
  resources/testcases/datatype_inference_consistency/with-source.rls
  resources/testcases/datatype_inference_consistency/with-source/b.csv
  resources/testcases/datatype_inference_consistency/with-source/c.csv
  resources/testcases/join_by_eq_constraint/string/literalInBody.csv
Labels: bug, logical, type system

#392 Fix bug with unknown constants in filter expressions
  nemo-physical/src/arithmetic/expression.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/tabular/operations/triescan_prune.rs
  nemo-physical/src/tabular/operations/triescan_select.rs
  nemo/src/model/rule_model/term.rs
  resources/testcases/datalog_constants/run.rls
  resources/testcases/datalog_constants/run/Unknown.csv
Labels: bug
