Repository knowsys/nemo, pull requests merged in 2024-06, with the labels that each got.

#482 fix RowScan::advance calling up too often
  nemo-physical/src/columnar/operations/subtract.rs
  nemo-physical/src/tabular/operations/projectreorder.rs
  nemo-physical/src/tabular/rowscan.rs
  nemo-physical/src/tabular/trie.rs
  resources/testcases/regression/datatypes/mixed/numeric.rls
  resources/testcases/regression/datatypes/mixed/numeric/P.csv
  resources/testcases/regression/datatypes/mixed/projection.rls
  resources/testcases/regression/datatypes/mixed/projection/result.csv
Labels: bug

#486 Handle HttpResources as raw bytes, not as text
  nemo/src/io/resource_providers/http.rs
Labels: bug, io

#491 Add unary builtin function for reversing a string
  nemo-physical/src/function/definitions.rs
  nemo-physical/src/function/definitions/string.rs
  nemo-physical/src/function/tree.rs
  nemo/src/execution/planning/operations/term.rs
  nemo/src/model/rule_model/term.rs
  resources/testcases/arithmetic/builtins.rls
  resources/testcases/arithmetic/builtins/result.csv
Labels: enhancement, builtins

#494 Change StringSubstringLength to handle excessive lengths
  nemo-physical/src/function/definitions/string.rs
  nemo-physical/src/function/evaluation.rs
  nemo-physical/src/function/tree.rs
  nemo/src/model/rule_model/term.rs
  resources/testcases/arithmetic/builtins.rls
  resources/testcases/arithmetic/builtins/result.csv
Labels: enhancement, builtins

#495 Add Unicode support to String functions
  Cargo.lock
  nemo-physical/Cargo.toml
  nemo-physical/src/function/definitions/string.rs
Labels: enhancement, builtins

#497 Refactor loop-based unicode grapheme comparison to be slice-based
  nemo-physical/src/function/definitions/string.rs
Labels: builtins

#496 provide timing info in the python api
  .github/workflows/pr.yml
  nemo-physical/src/meta/timing.rs
  nemo-python/setup.cfg
  nemo-python/src/lib.rs
  nemo-python/tests/test_example.py
Labels: enhancement, python
