Repository knowsys/nemo, pull requests merged in 2025-03, with the labels that each got.

#626 Replace deprecated rio with oxrdfio
  Cargo.lock
  flake.lock
  nemo-wasm/src/lib.rs
  nemo/Cargo.toml
  nemo/src/chase_model/analysis/variable_order.rs
  nemo/src/io/formats/rdf.rs
  nemo/src/io/formats/rdf/error.rs
  nemo/src/io/formats/rdf/reader.rs
  nemo/src/io/formats/rdf/writer.rs
  nemo/src/rule_model/components/term/operation/operation_kind.rs
  resources/testcases/regression/load/rdf-invalid-prefixes/regression.yaml
  resources/testcases/regression/load/rdf-invalid-prefixes/run.rls
  resources/testcases/regression/load/rdf-invalid-prefixes/run/out.csv
  resources/testcases/regression/load/sources/invalid-prefixes.ttl
Labels: io, dependency, rdf

#628 External variables
  nemo-cli/src/cli.rs
  nemo-cli/src/main.rs
  nemo/src/parser/ast/rule.rs
  nemo/src/parser/ast/statement.rs
  nemo/src/parser/error.rs
  nemo/src/rule_model/components/rule.rs
  nemo/src/rule_model/components/term/primitive/ground.rs
  nemo/src/rule_model/error/translation_error.rs
  nemo/src/rule_model/translation.rs
  nemo/src/rule_model/translation/attribute.rs
  nemo/src/rule_model/translation/directive/import_export.rs
  nemo/src/rule_model/translation/fact.rs
  nemo/src/rule_model/translation/rule.rs
Labels: enhancement

#650 Perform slices on graphemes for string functions STRBEFORE and STRAFTER
  nemo-physical/src/function/definitions/string.rs
Labels: bug, builtins

#645 Bug/643 broken stdout
  nemo-physical/src/resource.rs
  nemo/src/chase_model/analysis/variable_order.rs
  nemo/src/io/export_manager.rs
  nemo/src/io/format_builder.rs
  nemo/src/io/formats.rs
  nemo/src/io/import_manager.rs
  nemo/src/rule_model/error/validation_error.rs
Labels: bug, io
