Repository knowsys/nemo, pull requests merged in 2025-05, with the labels that each got.

#675 Feature/670 dump facts
  nemo-cli/src/cli.rs
  nemo-cli/src/main.rs
  nemo-cli/tests/cli.rs
Labels: enhancement, io

#680 Generate a manpage and shell completion data for nemo-cli
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  flake.lock
  flake.nix
  nemo-cli/Cargo.toml
  nemo-cli/src/cli.rs
  nemo-cli/src/lib.rs
  nemo-physical/src/function/definitions/string.rs
  xtask/Cargo.toml
  xtask/src/bin_name.rs
  xtask/src/commands.rs
  xtask/src/commands/completions.rs
  xtask/src/commands/manpages.rs
  xtask/src/main.rs
Labels: enhancement

#683 Bring down miri runtime
  .github/workflows/pr.yml
  flake.nix
  nemo-physical/Cargo.toml
  nemo-physical/src/dictionary.rs
  nemo/src/execution/tracing/trace.rs
  nemo/src/io/formats/sparql.rs
  nemo/src/parser/ast/directive.rs
  nemo/src/parser/ast/expression.rs
  nemo/src/parser/ast/expression/complex/arithmetic.rs
  nemo/src/parser/ast/expression/complex/map.rs
  nemo/src/parser/ast/expression/complex/tuple.rs
  nemo/src/parser/ast/guard.rs
  nemo/src/parser/ast/program.rs
  nemo/src/parser/ast/rule.rs
  nemo/src/parser/ast/sequence/key_value.rs
  nemo/src/parser/ast/statement.rs
Labels: tests, co2

#685 Rename count_rows/facts functions to ..._in_memory
  nemo-cli/src/main.rs
  nemo-physical/src/management/database.rs
  nemo-physical/src/management/database/order.rs
  nemo-physical/src/management/database/storage.rs
  nemo-wasm/src/lib.rs
  nemo/src/execution/execution_engine.rs
  nemo/src/table_manager.rs
Labels: technical-debt, physical, logical, wasm

#686 Fix import of compressed RDF files via HTTP
  nemo-physical/src/resource.rs
  nemo/src/io/compression_format.rs
  nemo/src/io/formats/rdf.rs
  nemo/src/rule_model/error/validation_error.rs
Labels: bug

#687 Bump nixpkgs & dependencies
  Cargo.lock
  flake.lock
  flake.nix
  nemo-cli/Cargo.toml
  nemo-language-server/Cargo.toml
  nemo-python/Cargo.toml
  nemo-python/src/lib.rs
  nemo-wasm/Cargo.toml
  nemo/Cargo.toml
  nemo/src/parser.rs
  nemo/src/rule_model/translation.rs
Labels: infrastructure, dependency
